-- 코드를 입력하세요
WITH ABC AS (
    SELECT MEMBER_ID, COUNT(*) AS NUM
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY NUM DESC LIMIT 1
)

SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
    FROM REST_REVIEW A, MEMBER_PROFILE B, ABC
    WHERE A.MEMBER_ID = B.MEMBER_ID AND B.MEMBER_ID = ABC.MEMBER_ID
    ORDER BY REVIEW_DATE, REVIEW_TEXT