-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
    FROM BOOK A
    JOIN (SELECT BOOK_ID, SUM(SALES) AS SALES
         FROM BOOK_SALES
         WHERE SALES_DATE LIKE '2022-01%'
         GROUP BY BOOK_ID) B ON A.BOOK_ID = B.BOOK_ID
    GROUP BY A.CATEGORY
    ORDER BY CATEGORY